{% set name = "json5" %}
{% set version = "0.9.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/json5-{{ version }}.tar.gz
  sha256: 20a255981244081d5aaa4adc90d31cdbf05bed1863993cbf300b8e2cd2b6de88

build:
  entry_points:
    - pyjson5=json5.tool:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0

test:
  imports:
    - json5
  commands:
    - pip check
    - pyjson5 --help
  requires:
    - pip

about:
  home: https://github.com/dpranke/pyjson5
  summary: A Python implementation of the JSON5 data format.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - ian-r-rose
